//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExpenseDbcontext : DbContext
    {
        public ExpenseDbcontext()
            : base("name=ExpenseDbcontext")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<Total_expenseLimit> Total_expenseLimit { get; set; }
        public DbSet<ExpenseData> ExpenseDatas { get; set; }

        public class ViewModel
        {
            public Category category { get; set; }
            public ExpenseData exData { get; set; }
        }
    }
}
